config/routes.rb
Depot1::Application.routes.draw do
  resources :reply_topics

  resources :votes

 get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :line_items

  resources :carts

  get "store/index"
    resources :products do
    get :who_bought, :on => :member
  end

  resources :products

    root :to =>'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Online Vote and Post System</title>
<%= stylesheet_link_tag "scaffold" %>
<%= stylesheet_link_tag "depot" , :media => "all" %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<body id="store">
<div id="banner">
<%= image_tag("ncsu12.png" ) %>
<%= @page_title || "ECE/CSC517 PROJECT1" %>
</div>
<div id="columns">
  <div id="side">

  <a href="  http://localhost:3000">Home</a><br />
  <a href="  http://localhost:3000/users/new">Create User</a><br />
  <a href="  http://localhost:3000/login">Login</a><br />
  <% if session[:user_id] %>
  <br />
  <%  @admin_flag = 'No' %>
  <%= link_to 'Post and Reply', products_path %><br />
  <%  if User.find(session[:user_id]).admin == 1 %>
  <%  @admin_flag = 'Yes' %>
  <%= link_to 'Users', users_path %><br />
  <% end %>
  <br />

  <tag> Welcome: <%= User.find(session[:user_id]).name%></tag> </br>
  <tag> Administrator: <%= @admin_flag %></tag></br>

  <%= button_to 'Logout', logout_path, :method => :delete %>
  <% end %>
  </div>

<div id="main">
<%= yield %>
</div>
</div>
</body>
</html>